# Generated by Django 5.0.7 on 2026-06-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Имя клиента')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='Телефон')),
                ('messenger', models.CharField(blank=True, max_length=120, verbose_name='WhatsApp/Telegram')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='Источник')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Материал')),
                ('unit', models.CharField(choices=[('ml', 'мл'), ('l', 'л'), ('m2', 'м²'), ('pcs', 'шт'), ('g', 'г'), ('kg', 'кг')], default='pcs', max_length=20, verbose_name='Ед. изм.')),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Остаток')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость за ед.')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Минимальный остаток')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Услуга')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80, verbose_name='Марка')),
                ('model', models.CharField(max_length=80, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('plate', models.CharField(blank=True, max_length=40, verbose_name='Госномер')),
                ('vin', models.CharField(blank=True, max_length=40, verbose_name='VIN')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='Цвет')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='crm.customer', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('new', 'Принят'), ('work', 'В работе'), ('ready', 'Готов'), ('done', 'Выдан'), ('cancel', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('date_in', models.DateTimeField(auto_now_add=True, verbose_name='Дата приема')),
                ('planned_out', models.DateTimeField(blank=True, null=True, verbose_name='План выдачи')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('materials_written_off', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.car', verbose_name='Авто')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена ед.')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='crm.material')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='crm.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Дата и время записи')),
                ('duration_minutes', models.PositiveIntegerField(default=180, verbose_name='Длительность, минут')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('arrived', 'Приехал'), ('work', 'В работе'), ('ready', 'Готово'), ('done', 'Завершено'), ('cancel', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.car', verbose_name='Автомобиль')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer', verbose_name='Клиент')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.service', verbose_name='Услуга')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='crm.workorder', verbose_name='Заказ-наряд')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.workorder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.service', verbose_name='Услуга')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Норма расхода')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.material')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='crm.service')),
            ],
            options={
                'unique_together': {('service', 'material')},
            },
        ),
    ]
